synocli-file: update tools and add pixz (#6288)
* synocli-file: update tools

- update detox to v2.0.0
- update eza v0.20.0
- update fd to v10.2.0
- update fdupes to v2.3.2 and add sqlite for optional caches
- update jdupes to v1.28.0 and libjodycode to v3.1.1
- update less to v661
- update lsd to v1.1.5
- update lzip to v1.24.1
- update mc to v4.8.32
- update micro to v2.0.14
- update nano to v8.2
- update pcre2 to v10.44
- update ripgrep to v14.1.1
- update tree to v2.1.3

* update fd for qoriq

- use fd 10.2.0 for qoriq with rust toolchain 1.82.0

* globally use different mirror for https://download.gnome.org/sources

- use different mirror since github workflow often uses an invalid mirror mirror2.sandyriver.net

* use latest cross/fd for qoriq

* revert unintended changes

* new package libarchive

* First pass at spk build

 - also fix license

* libarchive is not a pkg but just a depdendency

 - build from pre-configured tarball instead of raw source
 - which seems to support GNU configure
 - libcrytpo is runtime dependency
 - don't include bsd* cli; just shared object only

* new DIY package: pixz

 - patched to allow cross-compile

* Disable iconv for libarchive

I have no idea why. But spk/synocli-file would not build pixz. However,
cross/libarchive and diyspk/pigz both built standalone just fine.

Also documenting some other strange and no-determininistic artifacts
linked to build enviornment.

* Add pixz to synocli-file

* Proper build env dependency for libarchive

* pixz: fix undefined reference to rpl_malloc

* libarchive: whoops must include native dependency

* pixz: bump rev; ready for prime time

* Update cross/libarchive/PLIST

Link shared object aliases instead of copy.

Co-authored-by: hgy59 <hpgy59@gmail.com>

* add pixz

 - also clean up kruft

* Blindly disabling hi3535-6.2.4 build that's failing

* Whoops. Actually disable CI build

* improve cross/libarchive

- disable to build tools (we want the library only)
- document the need to build without libiconv
- disable static build and add code optimization to minimize library size
- libarchive builds without native/autoconf

* adjustments for pixz

- use configure parameter to avoid the AC_CHECK_FILE patch
- do not disable build for ARMv7L_ARCHS
- update changelog for synocli-file package

* rigprep: add pcre2 feature

- in the previous version (14.1.0) this feature (and simd-accel) was enabled by default
- since simd-accel has been removed for stable toolchains, we have to specify pcre2

* remove native/autoconf

* ripgrep: fix to find libpcre2 at runtime

---------

Co-authored-by: Curtis Doty <Curtis@GreenKey.net>